-- -----------------------------------------------------
-- TABLE ROLES
-- -----------------------------------------------------
CREATE TABLE ROLES (
  ID_ROL NUMERIC(6) NOT NULL PRIMARY KEY,
  NOMBRE VARCHAR2(65) NOT NULL,
  DESCRIPCION VARCHAR2(120) NULL,
  ESTADO CHAR(1) DEFAULT '1'  
);

CREATE SEQUENCE SEQ_ROL;

-- -----------------------------------------------------
-- TABLE TIPODOCUMENTOS
-- -----------------------------------------------------
CREATE TABLE TIPODOCUMENTOS (
  ID_TIPODOC NUMERIC(6) NOT NULL PRIMARY KEY,
  DESCRIPCION VARCHAR2(120) NOT NULL,
  LOGITUD INT NOT NULL
);

CREATE SEQUENCE SEQ_TIPODOCUMENTO;

-- -----------------------------------------------------
-- TABLE DEPARTAMENTOS
-- -----------------------------------------------------
CREATE TABLE DEPARTAMENTO(
	ID_DEPARTAMENTO NUMBER  NOT NULL PRIMARY KEY,
	NOM_DEPARTAMENTO VARCHAR2(130) NOT NULL
);

CREATE SEQUENCE SEQ_DEPARTAMENTO;

-- -----------------------------------------------------
-- TABLE PROVINCIAS
-- -----------------------------------------------------
CREATE TABLE PROVINCIA(
	ID_PROVINCIA NUMBER NOT NULL PRIMARY KEY,
	ID_DEPARTAMENTO NUMBER NOT NULL,
	NOM_PROVINCIA VARCHAR2(130) NOT NULL,
	FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTO (ID_DEPARTAMENTO)
);


CREATE SEQUENCE SEQ_PROVINCIA;

-- -----------------------------------------------------
-- TABLE DISTRITO
-- -----------------------------------------------------
CREATE TABLE DISTRITOS(
	ID_DISTRITO NUMBER NOT NULL PRIMARY KEY,
	ID_PROVINCIA NUMBER NOT NULL,
	NOM_DISTRITO VARCHAR2(130) NOT NULL,
	FOREIGN KEY (ID_PROVINCIA) REFERENCES PROVINCIA (ID_PROVINCIA)
);

CREATE SEQUENCE SEQ_DISTRITO;

-- -----------------------------------------------------
-- TABLE CLIENTES
-- -----------------------------------------------------
CREATE TABLE CLIENTES (
  ID_CLIENTE NUMERIC(6) NOT NULL PRIMARY KEY,
  ID_ROL NUMERIC(6) NOT NULL,
  ID_TIPODOC NUMERIC(6) NOT NULL,
  ID_DISTRITO NUMERIC(6) NOT NULL,
  NOMBRE VARCHAR2(150) NOT NULL,
  APELLIDO_PAT VARCHAR2(100) NOT NULL,
  APELLIDO_MAT VARCHAR2(100) NOT NULL,
  DIRECCION VARCHAR2(255) NULL,
  EMAIL VARCHAR2(150) NOT NULL,
  NUM_DOC VARCHAR2(255) NOT NULL,
  TELEFONO VARCHAR2(45) NULL,
  CLAVE VARCHAR2(120) NOT NULL,
  ESTADO CHAR(1) DEFAULT '1',
  FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID_ROL),
  FOREIGN KEY (ID_TIPODOC) REFERENCES TIPODOCUMENTOS (ID_TIPODOC),
  FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITOS (ID_DISTRITO)
);

CREATE SEQUENCE SEQ_CLIENTE;

-- -----------------------------------------------------
-- TABLE PRODUCTOS
-- -----------------------------------------------------
CREATE TABLE PRODUCTOS (
  ID_PRODUCTO NUMERIC(6) NOT NULL PRIMARY KEY,
  DETALLE VARCHAR2(255) NOT NULL,
  ESTADO CHAR(1) DEFAULT '1',
  MONTO NUMERIC(12,9) NOT NULL
);

CREATE SEQUENCE SEQ_PRODUCTO;

-- -----------------------------------------------------
-- TABLE QUEJAS
-- -----------------------------------------------------
CREATE TABLE QUEJAS (
  ID_QUEJA NUMERIC(6) NOT NULL PRIMARY KEY,
  DESCRIPCION VARCHAR2(255) NULL,
  ESTADO CHAR(1) DEFAULT '1'
);

CREATE SEQUENCE SEQ_QUEJA;

-- -----------------------------------------------------
-- TABLE SOLICITUDES
-- -----------------------------------------------------
CREATE TABLE SOLICITUDES (
  ID_SOLICITUD NUMERIC(6) NOT NULL PRIMARY KEY,
  ID_CLIENTE NUMERIC(6) NOT NULL,
  ID_DISTRITO NUMERIC(6) NOT NULL,
  ID_PRODUCTO NUMERIC(6) NOT NULL,
  ID_QUEJA NUMERIC(6) NOT NULL,
  FECHA_REGISTRO DATE NOT NULL,
  TIPO_SOLICITUD VARCHAR2(45) NOT NULL,
  ESTADO VARCHAR2(45) NOT NULL,
  DESCRIPCION_ESTADO VARCHAR2(255) NOT NULL,
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
  FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITOS (ID_DISTRITO),
  FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS (ID_PRODUCTO),
  FOREIGN KEY (ID_QUEJA) REFERENCES QUEJAS (ID_QUEJA)
);

CREATE SEQUENCE SEQ_SOLICITUD;

-- -----------------------------------------------------
-- TABLE DETALLE
-- -----------------------------------------------------
CREATE TABLE DETALLE (
  ID_TIPOSOLICITUD NUMERIC(6) NOT NULL PRIMARY KEY,
  FECHA_REGISTRO DATE NOT NULL,
  ESTADO VARCHAR2(45) NOT NULL,
  DESCRIPCION_ESTADO VARCHAR2(255) NULL,
  ID_SOLICITUD NUMERIC(6) NOT NULL,
  FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUDES (ID_SOLICITUD)
);

CREATE SEQUENCE SEQ_DETALLE;


-- ######################################################
-- SENTENCIAS SQL
-- ######################################################

SELECT *FROM CLIENTES;
























